# Generated by Django 5.0.14 on 2026-03-11 15:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Hospital Name"),
                ),
                ("lon", models.FloatField(verbose_name="Longitude")),
                ("lat", models.FloatField(verbose_name="Latitude")),
                ("fid", models.IntegerField(verbose_name="Field ID")),
                ("beds", models.IntegerField(default=1, verbose_name="Number of Beds")),
                (
                    "province_name",
                    models.CharField(max_length=100, verbose_name="Province"),
                ),
                (
                    "province_code",
                    models.CharField(max_length=1, verbose_name="Province Code"),
                ),
                (
                    "geometry_field",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
            ],
        ),
    ]
