# Generated by Django 5.0.14 on 2026-03-11 16:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Boundary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adm0_en", models.CharField(max_length=255)),
                ("adm0_pcode", models.CharField(max_length=255)),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Province Name"),
                ),
                ("pcode", models.CharField(max_length=1, verbose_name="Province Code")),
                (
                    "mpoly",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
            options={
                "verbose_name_plural": "Boundaries",
            },
        ),
    ]
